from __future__ import annotations

from typing import Protocol

from ai_org.domain.models import Approval, AuditEvent, Project, Task, WorkerRun


class Repository(Protocol):
    def add_project(self, project: Project) -> None: ...
    def get_project(self, project_id: str) -> Project | None: ...
    def get_project_by_idempotency_key(self, key: str) -> Project | None: ...
    def update_project(self, project: Project, expected_version: int) -> None: ...

    def add_task(self, task: Task) -> None: ...
    def get_task(self, task_id: str) -> Task | None: ...
    def list_tasks(self, project_id: str) -> list[Task]: ...
    def update_task(self, task: Task, expected_version: int) -> None: ...

    def add_worker_run(self, worker_run: WorkerRun) -> WorkerRun: ...
    def get_worker_run(self, run_id: str) -> WorkerRun | None: ...
    def get_worker_run_by_idempotency_key(self, key: str) -> WorkerRun | None: ...
    def list_worker_runs(self, task_id: str | None = None) -> list[WorkerRun]: ...
    def update_worker_run(self, worker_run: WorkerRun, expected_version: int) -> None: ...

    def add_approval(self, approval: Approval) -> Approval: ...
    def get_approval(self, approval_id: str) -> Approval | None: ...
    def get_approval_by_idempotency_key(self, key: str) -> Approval | None: ...
    def list_approvals(self, project_id: str) -> list[Approval]: ...
    def update_approval(self, approval: Approval, expected_version: int) -> None: ...

    def add_audit_event(self, event: AuditEvent) -> None: ...
    def list_audit_events(self, project_id: str) -> list[AuditEvent]: ...


class UnitOfWork(Protocol):
    repo: Repository

    def __enter__(self) -> UnitOfWork: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
